export const metadata = {
  title: 'Asan Melody',
  description: 'Generated by NEOS',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
